### ISSUE TITLE
locales with interpolation do not maintain valid syntax after translation

### ISSUE THREAD

**Issue by aseroff** [midwire/tr4n5l4te#11]
### Expected Behavior

Translate a locale file with a line like `sample_key: sample string with %{interpolation}`
Expect translation to be `sample_key: texto translado con %{interpolation}`

### Actual Behavior

Result is inappropriate spaces between % and {, and may translate the interpolation key
`sample_key: texto translado con% {interpolato}`

### Steps to reproduce the problem

See above. Can provide more details if necessary.

---
* Current Version: 0.1.18
* Operating System: mac

**Comment by aseroff** [comment]
I think this could be accomplished as so, with `var + i` being replaced with a some value that won't get translated by google.
    
  def process(hash)
      hash.each_with_object({}) do |pair, h|
        key, value = pair
        vars = value.scan(/%{+.*}+/)
        vars.each_with_index{|v, i| str.gsub(v, 'var' + i.to_s)}
        h[key] = value.is_a?(Hash) ? process(value) : translate(value)
        vars.each_with_index{|v, i| str.gsub('var' + i.to_s, v) }
        h
      end
    end

**Comment by aseroff** [comment]
Although I'm sure the translation's quality would be affected.

**Comment by midwire** [comment]
Thanks Andrew.  I’ll get to these issues ASAP.

**Comment by aseroff** [comment]
I'm sorry that I am not able to provide a PR with these changes and appropriate tests at the moment.

Thank you for this project though. Cheers.

**Comment by midwire** [comment]
So, apparently Google has changed this behavior since I originally wrote this code.  It did not previously add the space after the `%` for the interpolation.  I'm thinking along the same lines as you, in that it would probably be best to remove the whole interpolation piece before translating it and then adding it back in wherever the place holder was.   I was starting down the path of just the returned string by removing the extra space but at some point Google may munge it up even further.  A fix is on the way.

**Comment by midwire** [comment]
I'll update the gem shortly.

**Comment by aseroff** [comment]
Awesome. I can't imagine it's easy to maintain a tool that relies on the consistency of a Google UI.
Thanks!
